// Manual, art-directed palette and presentation per gym leader — see
// docs/design/DESIGN.md. One base color per leader; <ThemeScope> derives the
// -dim/-soft variants from it via color-mix() so every leader theme is
// generated by the same formula instead of hand-tuned shade-by-shade.
//
// Keyed by `LeaderSummary.id` (shared/apiTypes.ts), so screens can look up a
// theme from data they're already fetching.

import boulderBadge from '../assets/badges/boulder.png';
import brockPortrait from '../assets/leaders/brock.png';

export interface LeaderTheme {
  id: string;
  label: string;
  /** Base color the -dim/-soft variants are derived from. */
  primary: string;
  /** Splash portrait shown behind IntroScreen's shadow silhouette + sprite. */
  portrait: string;
  /** Gym badge icon, pinned to the intro heading box. */
  badge: string;
  /** Type whose swatch (typeColors.ts) drives the splash's shadow silhouette
   * and the heading box's comic-panel fill — the leader's thematic type,
   * not necessarily every one of their Pokémon's type. */
  typeKey: string;
  /** Numeric id fed to the Showdown replay widget's `replayid` field, which
   * derives its backdrop and BGM choice from it — see `DEFAULT_SCENE_ID` in
   * battle/replayLog.ts for how a value is picked. */
  sceneId: number;
  /** Splash portrait sizing/position, fed to intro.css as CSS custom
   * properties instead of the hardcoded numbers it used to carry for Brock
   * alone. `width` and `offsetTop` size and place `.leader-splash-portrait`;
   * `reservedHeight` is how much flow space `.leader-splash` reserves below
   * the title so the heading/rules text starts clear of the art. */
  portraitMetrics: {
    width: number;
    reservedHeight: number;
    offsetTop: number;
  };
}

export const leaderThemes: Record<string, LeaderTheme> = {
  brock: {
    id: 'brock',
    label: 'Brock',
    primary: '#8b6c3e',
    portrait: brockPortrait,
    badge: boulderBadge,
    typeKey: 'Rock',
    // 142 % 19 === 9 -> bg-earthycave.jpg, 142 % 15 === 7 -> the Kanto gym
    // leader BGM. Together: "Pewter Gym" (see replayLog.ts).
    sceneId: 142,
    portraitMetrics: { width: 510, reservedHeight: 480, offsetTop: 56 },
  },
};
