// Manual, art-directed palette per gym leader — see docs/design/DESIGN.md.
// One base color per leader; <ThemeScope> derives the -dim/-soft variants
// from it via color-mix() so every leader theme is generated by the same
// formula instead of hand-tuned shade-by-shade.
//
// Keyed by the same id the battle API already returns as `stageId`
// (shared/apiTypes.ts), so screens can look up a theme from data they're
// already fetching.

export interface LeaderTheme {
  id: string;
  label: string;
  /** Base color the -dim/-soft variants are derived from. */
  primary: string;
}

export const leaderThemes: Record<string, LeaderTheme> = {
  brock: { id: 'brock', label: 'Brock', primary: '#8b6c3e' },
};
