// Manual, art-directed palette and presentation per gym leader — see
// docs/design/DESIGN.md. One base color per leader; <ThemeScope> derives the
// -dim/-soft variants from it via color-mix() so every leader theme is
// generated by the same formula instead of hand-tuned shade-by-shade.
//
// Keyed by `LeaderSummary.id` (shared/apiTypes.ts), so screens can look up a
// theme from data they're already fetching.

import boulderBadge from '../assets/badges/boulder.png';
import brockPortrait from '../assets/leaders/brock.png';
import mistyPortrait from '../assets/leaders/misty.png';

export interface LeaderTheme {
  id: string;
  label: string;
  /** Base color the -dim/-soft variants are derived from. */
  primary: string;
  /** Splash portrait shown behind IntroScreen's shadow silhouette + sprite.
   * Optional: a leader can ship (config, copy, roster) before its art does -
   * IntroScreen skips the whole splash-portrait block, not just the `<img>`,
   * when this is absent, rather than rendering a broken image. */
  portrait?: string;
  /** Gym badge icon, pinned to the intro heading box. Same missing-art
   * handling as `portrait`. */
  badge?: string;
  /** Type whose swatch (typeColors.ts) drives the splash's shadow silhouette
   * and the heading box's comic-panel fill — the leader's thematic type,
   * not necessarily every one of their Pokémon's type. */
  typeKey: string;
  /** Numeric id fed to the Showdown replay widget's `replayid` field, which
   * derives its backdrop and BGM choice from it — see `DEFAULT_SCENE_ID` in
   * battle/replayLog.ts for how a value is picked. */
  sceneId: number;
  /** Splash portrait sizing/position, fed to intro.css as CSS custom
   * properties instead of the hardcoded numbers it used to carry for Brock
   * alone. `width` and `offsetTop` size and place `.leader-splash-portrait`;
   * `reservedHeight` is how much flow space `.leader-splash` reserves below
   * the title so the heading/rules text starts clear of the art. */
  portraitMetrics: {
    width: number;
    reservedHeight: number;
    offsetTop: number;
  };
}

export const leaderThemes: Record<string, LeaderTheme> = {
  brock: {
    id: 'brock',
    label: 'Brock',
    primary: '#8b6c3e',
    portrait: brockPortrait,
    badge: boulderBadge,
    typeKey: 'Rock',
    // 142 % 19 === 9 -> bg-earthycave.jpg, 142 % 15 === 7 -> the Kanto gym
    // leader BGM. Together: "Pewter Gym" (see replayLog.ts).
    sceneId: 142,
    portraitMetrics: { width: 510, reservedHeight: 480, offsetTop: 56 },
  },
  misty: {
    id: 'misty',
    label: 'Misty',
    // typeColors.Water.regular (#2980EF) pushed darker/more saturated for a
    // flat highlight-bar fill, same direction Brock's own primary took off
    // Rock's muted wiki color - see docs/design/DESIGN.md.
    primary: '#0c57b6',
    portrait: mistyPortrait,
    // No badge yet (.../badges/cascade.png) - the field is optional
    // precisely for this, see LeaderTheme. IntroScreen renders without the
    // badge until it lands; nothing else about the theme is blocked on it.
    typeKey: 'Water',
    // 127 % 19 === 13 -> bg-leaderwallace.jpg (Wallace, Emerald's Water gym
    // leader/champion - the closest thing this backdrop set has to a Water
    // gym), 127 % 15 === 7 -> the same Kanto gym leader BGM Brock uses
    // (bgmNum 8 is generic, not Rock-specific). See replayLog.ts.
    sceneId: 127,
    // Same numbers as Brock's, pending real art to measure against - see
    // portrait note above.
    portraitMetrics: { width: 510, reservedHeight: 480, offsetTop: 56 },
  },
};
